### ISSUE TITLE
Broken documentation link in README (points to a 404 page)

### ISSUE THREAD

**Issue by david-smejkal** [longclawshop/longclaw#480]
# ISSUE\_TEMPLATE

* longclaw version: n/a
* Django version: n/a
* Python version: n/a

## Description

Documentation is pointed to a dead link.
README points to [https://jamesramm.github.io/longclaw/](https://jamesramm.github.io/longclaw/) which throws 404.
It needs to be changed to point to [https://longclawshop.github.io/longclaw/](https://longclawshop.github.io/longclaw/) instead.

**Comment by akshayaureatelabs** [comment]
@david-smejkal  Hello,


Open the `README` file in your code editor.
Locate the link that points to the documentation (i.e. `https://jamesramm.github.io/longclaw/`).
Replace the old link with the new link (i.e. `https://longclawshop.github.io/longclaw/`).
Save the changes to the `README` file.
Test the link by clicking on it in the `README` file and verifying that it takes you to the correct documentation page.
Once you've completed these steps, the link in the `README` file should point to the correct documentation page and users will be able to access it without encountering a `404 error`.

**Comment by akshayaureatelabs** [comment]
@david-smejkal Sounds Good!
